name: dooz
favicon: null
layout_spectrum: 0
typography_spectrum: 0.33899
title: ' {}&â‚¬ => Work in progress, check back in a month... :)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5c3b1'
    - '#5d624f'
    - '#faecd0'
    - '#332b17'
    - '#f16e2f'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
